name: Main workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install Dependencies
      run: npm ci
    - name: Run eslint
      run: npm run lint
      
  build:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [lint]
   
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install Dependencies
      run: npm ci
    - name: Build demo site
      run: npm run build
    - name: Upload demo site
      uses: actions/upload-artifact@v1
      with:
        name: storybook-demo
        path: demo
 
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: demo
    env:
      DEPLOY_TOKEN: ${{secrets.deploy_token}}
      USER_NAME: andy770921
      USER_EMAIL: andy770921@yahoo.com.tw
      PUBLISH_DIR: ./demo
    
    steps:
    - name: Download demo site
      uses: actions/download-artifact@v1
      with:
        name: demo
    - name: Deploy demo site
      run: |
        cd $PUBLISH_DIR
        git init
        git config --local user.email $USER_EMAIL
        git config --local user.name $USER_NAME
        git remote add origin https://$DEPLOY_TOKEN@github.com/$GITHUB_REPOSITORY.git
        git checkout -b gh-pages
        git add --all
        git commit -m "Deploy to GitHub Pages"
        git push origin gh-pages -f